name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0677b13a0206b5c5e1d4d24f5054bbc5f73e54a7fcac50a480768da88c2de68"

[versions]
forge = "43.3.2"
minecraft = "1.19.2"
