name = "Create-Prepare-to-Dye"
author = "yarden-zamir"
version = "1.232.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c954901e4ccafa53e67eefd2bb2fc320e85961e379dd43995a2c29923af9e82e"

[versions]
forge = "43.4.4"
minecraft = "1.19.2"
