# Used to store server-related config file on the client
# Set it to a single value on different servers if you want them to share config
server_id = "d8eb5894-6b75-48f1-8d23-35728d362f72"
default_language = "en_us"
debug = false
disable_crowdin = false
check_for_updates = true

[host]
ip = "0.0.0.0"
port = 0

[voice]
# Supported sample rates:
# 8000
# 12000
# 24000
# 48000
sample_rate = 48000
keep_alive_timeout_ms = 15000
mtu_size = 1024
client_mod_required = false
client_mod_required_check_timeout_ms = 3000

[voice.proximity]
distances = [8, 16, 32]
default_distance = 16

[voice.opus]
# Opus application mode
# Supported values: VOIP, AUDIO, RESTRICTED_LOWDELAY
# Default is VOIP
mode = "VOIP"
# Opus bitrate
# Supported values: -1000 (auto), -1 (max), [500-512_000]
# Default is -1000
bitrate = -1000

[voice.weights]


