
[Reach]
	#Reach: how far away the player can place blocks using mirror/array etc.
	#Enable the crafting of reach upgrades to increase reach.
	#If disabled, reach is set to level 3 for survival players.
	enableReachUpgrades = true
	#Maximum reach in creative
	#Keep in mind that chunks need to be loaded to be able to place blocks inside.
	maxReachCreative = 200
	#Maximum reach in survival without upgrades
	#Reach upgrades are craftable consumables that permanently increase reach.
	#Set to 0 to disable Effortless Building until the player has consumed a reach upgrade.
	maxReachLevel0 = 20
	#Maximum reach in survival with one upgrade
	maxReachLevel1 = 50
	#Maximum reach in survival with two upgrades
	maxReachLevel2 = 100
	#Maximum reach in survival with three upgrades
	maxReachLevel3 = 200

[SurvivalBalancers]
	#Allows a survival player to break blocks that are far away, in addition to placing blocks.
	#Note: this allows insta-breaking of blocks in survival.
	breakFar = false
	#Increases the time to mine a block when breaking multiple at once.
	#Mining time depends on how many blocks, what type of blocks, and the percentage below.
	#Example: breaking 1 dirt + 1 obsidian takes the time of breaking 1 dirt + 1 obsidian.
	increasedMiningTime = true
	#How much the mining time of each additional block counts towards an increased mining time.
	#A percentage between 0% and 100%, where 0% is the same as disabling it,
	#and 100% takes as much time as breaking each block individually.
	#The block in front of you always counts as 100%.
	#Range: 0 ~ 200
	miningTimePercentage = 50
	#Determines what blocks can be replaced in survival.
	#-1: only blocks that can be harvested by hand (default)
	#0: blocks that can be harvested with wooden or gold tools
	#1: blocks that can be harvested with stone tools
	#2: blocks that can be harvested with iron tools
	#3: blocks that can be harvested with diamond tools
	#Range: -1 ~ 3
	quickReplaceMiningLevel = -1
	#How many placements are remembered for the undo functionality.
	undoStackSize = 10

[Visuals]
	#Show a block preview if you have a block in hand even in the 'Normal' build mode
	alwaysShowBlockPreview = false
	#How long the dissolve effect takes when placing blocks.
	#Default between 30 and 60 ticks, you can multiply that here.
	#Recommended values:
	#Snappy: 0.7
	#Relaxing: 1.5
	dissolveTimeMultiplier = 1.0
	#Switch to using the simple performance shader when placing more than this many blocks.
	shaderTreshold = 1500
	#Use fancy shaders while placing blocks
	useShaders = true

