
[general]
	#The speed at which time passes during the day.
	#Day is defined as any time between 23500 (middle of dawn) and 12500 (middle of dusk) the next day.
	#Vanilla speed: 1.0
	#Range: 0.0 ~ 24000.0
	daySpeed = 0.5
	#The speed at which time passes during the night.
	#Night is defined as any time between 12500 (middle of dusk) and 23500 (middle of dawn).
	#Vanilla speed: 1.0
	#Range: 0.0 ~ 24000.0
	nightSpeed = 2.0
	#When true, displays a clock in the sleep interface.
	displayBedClock = true
	#Accelerate the passage of weather at the same rate as the passage of time, making weather events
	#elapse faster while the passage of time is accelerated. Clear weather is not accelerated.
	#Note: This setting is not applicable if game rule doWeatherCycle is false.
	accelerateWeather = true

[sleep]
	#Enables or disables the sleep feature of this mod. Enabling this setting will modify the vanilla
	#sleep functionality and may conflict with other sleep mods. If disabled, the settings in the
	#messages section and the remaining settings in this section will not apply.
	enableSleepFeature = true
	#The minimum speed at which time passes when only 1 player is sleeping in a full server.
	#Range: 0.0 ~ 24000.0
	sleepSpeedMin = 1.0
	#The maximum speed at which time passes when all players are sleeping. A value of 120
	#is approximately equal to the time it takes to sleep in vanilla.
	#Range: 0.0 ~ 24000.0
	sleepSpeedMax = 120.0
	#The speed at which time passes when all players are sleeping.
	#Set to -1 to disable this feature (sleepSpeedMax will be used when all players are sleeping).
	#Range: -1.0 ~ 24000.0
	sleepSpeedAll = -1.0
	#Set to 'true' for the weather to clear when players wake up in the morning as it does in vanilla.
	#Set to 'false' to allow weather to pass realistically overnight if accelerateWeather is enabled.
	#Note: This setting is ignored if game rule doWeatherCycle is false.
	clearWeatherOnWake = true
	#When true, accelerates the random tick speed while sleeping. This allows things like crops and
	#grass to grow at the same rate as time is passing overnight. The modified random tick speed is the
	#sleep.baseRandomTickSpeed value times the current time speed. This means that as time moves faster, crops grow faster.
	#More information on the effects of random tick speed can be found here:
	#https://minecraft.fandom.com/wiki/Tick#Random_tick
	#WARNING: This setting manipulates the randomTickSpeed game rule. To modify the base random tick speed,
	#use the sleep.baseRandomTickSpeed config setting instead of changing the game rule directly.
	accelerateRandomTicking = true
	#The base random tick speed to use when sleep.accelerateRandomTickSpeed config is enabled.
	#Range: > 0
	baseRandomTickSpeed = 2

#This section defines settings for notification messages.
#All messages in this section support Minecraft formatting codes (https://minecraft.fandom.com/wiki/Formatting_codes).
#All messages in this section support variable substitution in the following format: ${variableName}
#Supported variables differ per message.
[messages]
	#This message is sent to morningMessageTarget after a sleep cycle has completed in it.
	#Available variables:
	#sleepingPlayers -> the number of players in the current dimension who were sleeping.
	#totalPlayers -> the number of players in the current dimension (spectators are not counted).
	#sleepingPercentage -> the percentage of players in the current dimension who were sleeping (does not include % symbol).
	morningMessage = ""
	#Sets the message type for the morning message.
	#SYSTEM: Appears as a message in the chat. (e.g., "Respawn point set")
	#GAME_INFO: Game information that appears above the hotbar (e.g., "You may not rest now, the bed is too far away").
	#Allowed Values: SYSTEM, GAME_INFO
	morningMessageType = "GAME_INFO"
	#Sets the target for the morning message.
	#ALL: Send the message to all players on the server.
	#DIMENSION: Send the message to all players in the current dimension.
	#SLEEPING: Only send the message to those who just woke up.
	#Allowed Values: ALL, DIMENSION, SLEEPING
	morningMessageTarget = "DIMENSION"
	#This message is sent to bedMessageTarget when a player starts sleeping.
	#Available variables:
	#player -> the player who started sleeping.
	#sleepingPlayers -> the number of players in the current dimension who are sleeping.
	#totalPlayers -> the number of players in the current dimension (spectators are not counted).
	#sleepingPercentage -> the percentage of players in the current dimension who are sleeping (does not include % symbol).
	inBedMessage = "${player} is now sleeping. [${sleepingPlayers}/${totalPlayers}]"
	#This message is sent to bedMessageTarget when a player gets out of bed (without being woken up naturally at morning).
	#Available variables:
	#player -> the player who left their bed.
	#sleepingPlayers -> the number of players in the current dimension who are sleeping.
	#totalPlayers -> the number of players in the current dimension (spectators are not counted).
	#sleepingPercentage -> the percentage of players in the current dimension who are sleeping (does not include % symbol).
	outOfBedMessage = "${player} has left their bed. [${sleepingPlayers}/${totalPlayers}]"
	#Sets the message type for inBedMessage and outOfBedMessage.
	#SYSTEM: Appears as a message in the chat (e.g., "Respawn point set").
	#GAME_INFO: Game information that appears above the hotbar (e.g., "You may not rest now, the bed is too far away").
	#Allowed Values: SYSTEM, GAME_INFO
	bedMessageType = "GAME_INFO"
	#Sets the target for inBedMessage and outOfBedMessage.
	#ALL: Send the message to all players on the server.
	#DIMENSION: Send the message to all players in the current dimension.
	#SLEEPING: Only send the message to players who are currently sleeping.
	#Allowed Values: ALL, DIMENSION, SLEEPING
	bedMessageTarget = "DIMENSION"

