
["Server Configs"]
	#Canister Capacity in mB
	"Capacity of Canisters" = 8000
	#Canister can be filled by spouts
	"Canister can be filled by spouts" = true
	#Combustibles do boom boom when on fire
	"Combustibles blow up" = true

	["Server Configs"."Diesel Engines"]

		["Server Configs"."Diesel Engines"."Tag Compatibility"]
			#forge:fuel tag compatibility
			"forge:fuel tag compatibility" = true
			#forge:ethanol tag compatibility
			"forge:ethanol tag compatibility" = true
			#forge:plantoil tag compatibility
			"forge:plantoil tag compatibility" = true
			#forge:biodiesel tag compatibility
			"forge:biodiesel tag compatibility" = true
			#forge:diesel tag compatibility
			"forge:diesel tag compatibility" = true
			#forge:gasoline tag compatibility
			"forge:gasoline tag compatibility" = true

		["Server Configs"."Diesel Engines"."Stress/Speed/Burn Rate Values"]
			#Diesel Engine Fuel fast burn rate per second
			"Diesel Engine Fuel fast burn rate" = 4
			#Diesel Engine Fuel slow burn rate per second
			"Diesel Engine Fuel slow burn rate" = 2
			#Speed of Slow Fuel Type in RPM
			"Speed of Slow Fuel Type" = 8.0
			#Speed of Fast Fuel Type in RPM
			"Speed of Fast Fuel Type" = 16.0
			#Strength of Weak Fuel Type in su
			"Strength of Weak Fuel Type" = 256.0
			#Strength of Strong Fuel Type in su
			"Strength of Strong Fuel Type" = 512.0

			["Server Configs"."Diesel Engines"."Stress/Speed/Burn Rate Values"."Engine Type Multipliers"]
				#Modular Diesel Engine Generated Stress Multiplier
				"Modular Diesel Engine Stress Multiplier" = 1.0
				#Huge Diesel Engine Generated Stress Multiplier
				"Huge Diesel Engine Stress Multiplier" = 1.123046875
				#Turbocharged Diesel Engine Speed Multiplier
				"Turbocharged Diesel Engine Speed Multiplier" = 4.0
				#Turbocharged Diesel Engine Burn Rate Multiplier
				"Turbocharged Diesel Engine Burn Rate Multiplier" = 3.0

	["Server Configs"."Oil Config"]
		#Normal oil chunks oil amount multiplier
		"Normal oil chunks oil amount multiplier" = 1.0
		#High oil chunks oil amount multiplier
		"High oil chunks oil amount multiplier" = 1.0
		#Max Oil Scanner Level
		"Max Oil Scanner Level" = 10000
		#Normal oil chunks percentage
		#Range: 0.0 ~ 100.0
		"Normal oil chunks percentage" = 5.0
		#High oil chunks percentage
		#Range: 0.0 ~ 100.0
		"High oil chunks percentage" = 5.0

		["Server Configs"."Oil Config".Distillation]
			#Whenever wide Distillation Towers go faster than the thin ones
			"Wide Distillation Tower Distill Faster" = true
			#Height of Distillation Tower level
			#Range: 1 ~ 3
			"Height of Distillation Tower level" = 1

