
[general]
	#The base amount of midair jumps every player has. This is summed with the amount of multi-jumps provided by equipment.
	#Range: 0 ~ 1024
	multiJumps = 1
	#The base coyote time every player has in ticks.  This is summed with the duration of coyote time provided by equipment.
	#Range: 0 ~ 65536
	coyoteTime = 3
	#The base step height every player has in blocks.
	#Range: 0.0 ~ 8.0
	stepHeight = 0.9
	#The base step height every player has in blocks when sneaking. It's highly recommended to keep this at the default value.
	#Range: 0.0 ~ 8.0
	stepHeightSneaking = 0.6
	#Additional base jump height in equivalent levels of the jump boost potion effect. Negative values possible.
	#Range: -128.0 ~ 127.0
	jumpHeightBoost = 0.0

