debug = false
disable_crowdin = false
check_for_updates = true

[activations.4aec07ba-d109-3345-9a0a-92022a116cd0]
toggle = false
type = "VOICE"
[[key_bindings]]
name = "key.plasmovoice.proximity.distance_increase"
any_context = false
category = "hidden"

[[key_bindings.keys]]
code = 61
type = "KEYSYM"

[[key_bindings]]
name = "key.plasmovoice.occlusion.toggle"
any_context = false
category = "key.plasmovoice.occlusion"

[[key_bindings.keys]]
code = 45
type = "KEYSYM"

[servers.3089cd6f-64b6-4af5-b9e5-83ee54a0595e.distances]
4aec07ba-d109-3345-9a0a-92022a116cd0 = 32


[voice]
disabled = false
microphone_disabled = false
activation_threshold = -60.0
input_device = ""
output_device = ""
disable_input_device = false
use_javax_input = true
microphone_volume = 1.0
noise_suppression = true
volume = 1.0
compressor_limiter = true
sound_occlusion = false
directional_sources = false
hrtf = false
stereo_capture = false

[voice.volumes.source_a1fd240d-f3f5-4feb-9c2a-6d0c377ee504]
volume = 1.0
[voice.volumes.source_ba1a7140-aacf-44f3-8f75-49dc45de61f7]
volume = 1.0
[voice.volumes.proximity]
volume = 1.0

[advanced]
visualize_voice_distance = true
visualize_voice_distance_on_join = false
compressor_threshold = -10
limiter_threshold = -6
directional_sources_angle = 145
stereo_sources_to_mono = false
panning = true
camera_sound_listener = true
exponential_volume_slider = true
exponential_distance_gain = true

[overlay]
show_activation_icon = true
activation_icon_position = "BOTTOM_CENTER"
show_source_icons = 0
show_static_source_icons = true
overlay_enabled = true
overlay_position = "TOP_LEFT"
overlay_style = "NAME_SKIN"

[overlay.source_states]
proximity = "ON"
